import { readFile, readdir, stat } from "node:fs/promises";
import { basename, dirname, extname, join, relative } from "node:path";
import JSZip from "jszip";
import { assertWithin, safeRealpath, stableId, type ParsedWork, type SourceDocument, type WorkAdapter, type WorkCandidate } from "@writing-mcp/core";

const supported = new Set([".md", ".markdown", ".txt", ".epub"]);
const titleOf = (path: string, content: string) => content.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? basename(path, extname(path));
const chapterOf = (title: string) => Number(title.match(/(?:第\s*)?(\d+)\s*(?:章|chapter)?/i)?.[1]) || undefined;
const codedError=(code:string,message:string,cause?:unknown)=>Object.assign(new Error(message,{cause}),{code});
const chineseDigits:Record<string,number>={"零":0,"〇":0,"○":0,"Ｏ":0,"０":0,"一":1,"二":2,"两":2,"三":3,"四":4,"五":5,"六":6,"七":7,"八":8,"九":9};
const chapterNumber=(value:string)=>{if(/^\d+$/.test(value))return Number(value);const [tens,ones]=value.split("十");if(value.includes("十"))return(tens?chineseDigits[tens]??0:1)*10+(ones?chineseDigits[ones]??0:0);return chineseDigits[value];};
const decodeText=(data:Uint8Array)=>{if(data[0]===0xef&&data[1]===0xbb&&data[2]===0xbf)return new TextDecoder("utf-8",{fatal:true}).decode(data.subarray(3));try{return new TextDecoder("utf-8",{fatal:true}).decode(data);}catch{try{return new TextDecoder("gb18030",{fatal:true}).decode(data);}catch(error){throw codedError("TEXT_ENCODING_UNSUPPORTED","Text is neither valid UTF-8 nor GB18030",error);}}};

function txtDocuments(file:string,root:string,workRef:string,content:string,mtimeMs:number):SourceDocument[]{
  const lines=content.replace(/\r\n?/g,"\n").split("\n"),headings:Array<{line:number;local:number;volume:number;title:string}>=[];let volume=1,previous=0;
  for(let line=0;line<lines.length;line++){const title=lines[line]!.trim(),match=/^(?:第([零〇○Ｏ０一二三四五六七八九十两\d]+)(?:章|回|节)|chapter\s+(\d+|[ivxlcdm]+))(?:\s+.*)?$/i.exec(title);if(!match)continue;const local=match[1]?chapterNumber(match[1]):Number(match[2]);if(!local)continue;if(previous&&local<=previous)volume++;headings.push({line,local,volume,title});previous=local;}
  if(!headings.length)return[];
  const rel=relative(root,file).replaceAll("\\","/"),documents:SourceDocument[]=[];
  if(headings[0]!.line>0){const preface=lines.slice(0,headings[0]!.line).join("\n").trim();if(preface)documents.push({documentRef:stableId("doc",workRef,rel,"preface"),relativePath:`${rel}#preface`,absolutePath:file,title:`${basename(file,extname(file))} preface`,kind:"document",content:preface,sourceStartLine:1,sourceMtimeMs:mtimeMs,sourceSize:Buffer.byteLength(preface)});}
  for(let index=0;index<headings.length;index++){const heading=headings[index]!,end=headings[index+1]?.line??lines.length,piece=lines.slice(heading.line,end).join("\n").trimEnd(),locator=`v${heading.volume}-c${heading.local}`;documents.push({documentRef:stableId("doc",workRef,rel,locator),relativePath:`${rel}#${locator}`,absolutePath:file,title:heading.title,kind:"chapter",content:piece,chapterNumber:index+1,sourceStartLine:heading.line+1,sourceMtimeMs:mtimeMs,sourceSize:Buffer.byteLength(piece)});}
  return documents;
}

async function filesUnder(path: string,root?:string,visited=new Set<string>()): Promise<string[]> {
  const real=await safeRealpath(path),safeRoot=root??real;assertWithin(safeRoot,real);if(visited.has(real))return[];visited.add(real);const info = await stat(real); if (info.isFile()) return supported.has(extname(real).toLowerCase()) ? [real] : [];
  const out: string[] = []; for (const entry of await readdir(real, { withFileTypes: true })) { if (entry.name.startsWith(".") || entry.name === "node_modules") continue; const child=join(real,entry.name);const childReal=await safeRealpath(child);assertWithin(safeRoot,childReal);if(entry.isDirectory()) out.push(...await filesUnder(childReal,safeRoot,visited)); else if(supported.has(extname(entry.name).toLowerCase())) out.push(childReal); } return out.sort();
}

async function epubDocuments(path:string,root:string):Promise<SourceDocument[]>{const data=await readFile(path);let zip:JSZip;try{zip=await JSZip.loadAsync(data);}catch(error){throw codedError("EPUB_INVALID_ZIP","EPUB is not a readable ZIP container",error);}const container=await zip.file("META-INF/container.xml")?.async("string");const opfPath=container?.match(/full-path=["']([^"']+)/)?.[1];if(!opfPath)throw codedError("EPUB_CONTAINER_MISSING","EPUB container does not declare an OPF package");const opf=await zip.file(opfPath)?.async("string");if(!opf)throw codedError("EPUB_OPF_MISSING","EPUB OPF package is missing");const manifest=new Map<string,string>();for(const m of opf.matchAll(/<item\b[^>]*\bid=["']([^"']+)["'][^>]*\bhref=["']([^"']+)["'][^>]*>/gi))manifest.set(m[1]!,m[2]!);const ids=[...opf.matchAll(/<itemref\b[^>]*\bidref=["']([^"']+)["']/gi)].map(m=>m[1]!);const opfDir=dirname(opfPath).replaceAll("\\","/");const info=await stat(path);const docs:SourceDocument[]=[];for(let i=0;i<ids.length;i++){const href=manifest.get(ids[i]!);if(!href)continue;let decodedHref:string;try{decodedHref=decodeURIComponent(href.split("#")[0]!);}catch(error){throw codedError("EPUB_HREF_INVALID",`EPUB manifest contains an invalid href: ${href}`,error);}const entryPath=join(opfDir,decodedHref).replaceAll("\\","/");const html=await zip.file(entryPath)?.async("string");if(!html)continue;const content=html.replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<br\s*\/?\s*>/gi,"\n").replace(/<\/p>|<\/h[1-6]>/gi,"\n").replace(/<[^>]+>/g,"").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/\n{3,}/g,"\n\n").trim();if(!content)continue;const title=content.split("\n").find(Boolean)?.slice(0,100)??`Chapter ${i+1}`;const rel=`${relative(root,path).replaceAll("\\","/")}#${entryPath}`;docs.push({documentRef:stableId("doc",path,entryPath),relativePath:rel,absolutePath:path,title,kind:"chapter",content,chapterNumber:chapterOf(title)??i+1,sourceMtimeMs:info.mtimeMs,sourceSize:info.size});}if(!docs.length)throw codedError("EPUB_NO_READABLE_SPINE","EPUB contains no readable spine chapters");return docs;}

export class GenericAdapter implements WorkAdapter {
  readonly kind="generic" as const;
  async discover(sourcePath:string):Promise<WorkCandidate[]>{try{const real=await safeRealpath(sourcePath);const files=await filesUnder(real);if(!files.length)return[];const directory=(await stat(real)).isDirectory();const root=directory?real:dirname(real);const title=directory?basename(real):basename(real,extname(real));return[{workRef:stableId("work","generic",real),title,rootPath:root,sourcePath:real,adapter:this.kind,capabilities:["documents","full_text","epub"]}];}catch(error){if(typeof error==="object"&&error&&"code" in error&&error.code==="PATH_NOT_ALLOWED")throw error;return[];}}
  async load(candidate:WorkCandidate):Promise<ParsedWork>{const files=await filesUnder(candidate.sourcePath??candidate.rootPath);const documents:SourceDocument[]=[];for(const file of files){const extension=extname(file).toLowerCase();if(extension===".epub"){documents.push(...await epubDocuments(file,candidate.rootPath));continue;}const info=await stat(file),content=decodeText(await readFile(file));if(extension===".txt"){const chapters=txtDocuments(file,candidate.rootPath,candidate.workRef,content,info.mtimeMs);if(chapters.length){documents.push(...chapters);continue;}}const title=titleOf(file,content);const label=(file+" "+title).toLowerCase();const kind=/chapter|章节|第\s*\d+\s*章/i.test(label)?"chapter":/characters?|角色|人物/.test(label)?"character":"document";documents.push({documentRef:stableId("doc",candidate.workRef,relative(candidate.rootPath,file)),relativePath:relative(candidate.rootPath,file).replaceAll("\\","/"),absolutePath:file,title,kind,content,chapterNumber:chapterOf(title),sourceMtimeMs:info.mtimeMs,sourceSize:info.size});}return{...candidate,documents};}
}
