import { DatabaseSync } from "node:sqlite";
import { mkdtemp, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, test } from "vitest";
import { stableId, WritingStore, type ParsedWork, type SourceDocument } from "@writing-mcp/core";

const document=(workRef:string,relativePath:string,content:string,ordinal=0):SourceDocument=>({documentRef:stableId("doc",workRef,String(ordinal)),relativePath,absolutePath:relativePath,title:`Document ${ordinal}`,kind:"document",content,sourceMtimeMs:1,sourceSize:content.length});
const workAt=(rootPath:string,documents:SourceDocument[]):ParsedWork=>({workRef:stableId("work","test",rootPath),title:"Test",rootPath,adapter:"generic",capabilities:[],documents});
const indexPath=(work:ParsedWork)=>join(work.rootPath,".writing-index",work.workRef.replace(":","-"),"index.sqlite");

describe("M2 index lifecycle",()=>{
  test("status reports an incompatible schema and incremental explicitly rebuilds it",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-schema-"));const work=workAt(root,[]);const dir=join(root,".writing-index",work.workRef.replace(":","-"));await mkdir(dir,{recursive:true});const seeded=new DatabaseSync(join(dir,"index.sqlite"));seeded.exec("PRAGMA user_version=1; CREATE TABLE obsolete(value TEXT);");seeded.close();const store=new WritingStore(work);try{const status=await store.index("status");expect(status.freshness).toBe("incompatible");expect(status.diagnostics[0]?.code).toBe("INDEX_SCHEMA_INCOMPATIBLE");const rebuilt=await store.index("incremental");expect(rebuilt.freshness).toBe("fresh");expect(rebuilt.diagnostics[0]?.code).toBe("INDEX_SCHEMA_REBUILT");const db=new DatabaseSync(indexPath(work),{readOnly:true});try{expect((db.prepare("PRAGMA user_version").get() as {user_version:number}).user_version).toBe(3);expect(()=>db.prepare("SELECT * FROM obsolete").all()).toThrow();expect(db.prepare("SELECT schema_version,current_revision FROM works").get()).toEqual({schema_version:3,current_revision:1});}finally{db.close();}}finally{store.close();await rm(root,{recursive:true,force:true});}});

  test("a failed incremental transaction preserves the previous revision and documents",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-rollback-"));const ref=stableId("work","test",root);const valid=workAt(root,[document(ref,"one.md","stable content")]);const firstStore=new WritingStore(valid);let revision=0;try{revision=(await firstStore.index("rebuild")).revision;}finally{firstStore.close();}const invalid=workAt(root,[document(ref,"duplicate.md","new one",1),document(ref,"duplicate.md","new two",2)]);const failingStore=new WritingStore(invalid);try{await expect(failingStore.index("incremental")).rejects.toThrow();}finally{failingStore.close();}const db=new DatabaseSync(indexPath(valid),{readOnly:true});try{expect(Number((db.prepare("SELECT MAX(revision) revision FROM index_revisions").get() as {revision:number}).revision)).toBe(revision);expect((db.prepare("SELECT relative_path FROM documents").all() as Array<{relative_path:string}>).map(row=>row.relative_path)).toEqual(["one.md"]);}finally{db.close();await rm(root,{recursive:true,force:true});}});

  test("a failed full rebuild preserves the active database and removes temporary files",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-atomic-"));const ref=stableId("work","test",root);const valid=workAt(root,[document(ref,"one.md","stable content")]);const first=new WritingStore(valid);try{await first.index("rebuild");}finally{first.close();}const invalid=workAt(root,[document(ref,"duplicate.md","new one",1),document(ref,"duplicate.md","new two",2)]);const failing=new WritingStore(invalid);try{await expect(failing.index("rebuild")).rejects.toThrow();}finally{failing.close();}const db=new DatabaseSync(indexPath(valid),{readOnly:true});try{expect((db.prepare("SELECT relative_path FROM documents").all() as Array<{relative_path:string}>).map(row=>row.relative_path)).toEqual(["one.md"]);expect((db.prepare("PRAGMA integrity_check").get() as {integrity_check:string}).integrity_check).toBe("ok");}finally{db.close();}const files=await readdir(join(root,".writing-index",valid.workRef.replace(":","-")));expect(files.filter(name=>name.includes(".tmp.")||name.endsWith(".previous"))).toEqual([]);await rm(root,{recursive:true,force:true});});

  test("status reports stale when semantic document state differs",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-freshness-"));const ref=stableId("work","test",root);const original=workAt(root,[{...document(ref,"one.md","unchanged content"),title:"Old title",kind:"document"}]);const first=new WritingStore(original);try{await first.index("rebuild");}finally{first.close();}const changed=workAt(root,[{...document(ref,"one.md","unchanged content"),title:"New title",kind:"chapter",chapterNumber:7,sourceStartLine:9}]);const second=new WritingStore(changed);try{const status=await second.index("status");expect(status.freshness).toBe("stale");expect(status.stats.updated).toBe(1);expect(status.diagnostics[0]?.code).toBe("INDEX_SOURCE_CHANGED");const updated=await second.index("incremental");expect(updated.revision).toBe(2);expect(updated.stats.updated).toBe(1);}finally{second.close();}const db=new DatabaseSync(indexPath(changed),{readOnly:true});try{expect(db.prepare("SELECT title,kind,chapter_number,source_start_line FROM documents").get()).toEqual({title:"New title",kind:"chapter",chapter_number:7,source_start_line:9});}finally{db.close();await rm(root,{recursive:true,force:true});}});

  test("source ordering participates in the semantic snapshot",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-order-snapshot-"));const ref=stableId("work","test",root);const one=document(ref,"one.md","one",1),two=document(ref,"two.md","two",2);const first=new WritingStore(workAt(root,[one,two]));try{await first.index("rebuild");}finally{first.close();}const reordered=workAt(root,[two,one]);const second=new WritingStore(reordered);try{const status=await second.index("status");expect(status.freshness).toBe("stale");expect(status.stats.updated).toBe(2);await second.index("incremental");}finally{second.close();}const db=new DatabaseSync(indexPath(reordered),{readOnly:true});try{expect(db.prepare("SELECT relative_path,source_ordinal FROM documents ORDER BY source_ordinal").all()).toEqual([{relative_path:"two.md",source_ordinal:0},{relative_path:"one.md",source_ordinal:1}]);}finally{db.close();await rm(root,{recursive:true,force:true});}});

  test("does not overwrite a user-managed cache gitignore",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-gitignore-"));const ref=stableId("work","test",root),cache=join(root,".writing-index");await mkdir(cache,{recursive:true});await writeFile(join(cache,".gitignore"),"custom-rule\n");const store=new WritingStore(workAt(root,[document(ref,"one.md","content")]));try{await store.index("rebuild");}finally{store.close();}expect(await readFile(join(cache,".gitignore"),"utf8")).toBe("custom-rule\n");await rm(root,{recursive:true,force:true});});

  test("recovers an interrupted atomic replacement before the next write",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-recovery-"));const ref=stableId("work","test",root),work=workAt(root,[document(ref,"one.md","content")]);const first=new WritingStore(work);try{await first.index("rebuild");}finally{first.close();}const active=indexPath(work),backup=`${active}.previous`,dir=join(root,".writing-index",work.workRef.replace(":","-"));await rename(active,backup);await writeFile(join(dir,"index.deadbeef.tmp.sqlite"),"orphan");const statusStore=new WritingStore(work);try{const status=await statusStore.index("status");expect(status.freshness).toBe("stale");expect(status.diagnostics[0]?.code).toBe("INDEX_RECOVERY_REQUIRED");}finally{statusStore.close();}const recovery=new WritingStore(work);try{const result=await recovery.index("incremental");expect(result.revision).toBe(1);expect(result.freshness).toBe("fresh");}finally{recovery.close();}expect(await readdir(dir)).not.toContain("index.deadbeef.tmp.sqlite");const db=new DatabaseSync(active,{readOnly:true});try{expect(db.prepare("SELECT COUNT(*) count FROM documents").get()).toEqual({count:1});}finally{db.close();await rm(root,{recursive:true,force:true});}});

  test("returns INDEX_BUSY when another live process owns the writer lock",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-lock-"));const ref=stableId("work","test",root),work=workAt(root,[document(ref,"one.md","content")]);const first=new WritingStore(work);try{await first.index("rebuild");}finally{first.close();}const dir=join(root,".writing-index",work.workRef.replace(":","-")),lock=join(dir,"write.lock");await writeFile(lock,JSON.stringify({pid:process.pid,token:"external-test-owner"}));const second=new WritingStore(work);try{await expect(second.index("incremental")).rejects.toMatchObject({code:"INDEX_BUSY"});}finally{second.close();await rm(lock,{force:true});await rm(root,{recursive:true,force:true});}});

  test("reclaims a writer lock left by a dead process",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-stale-lock-"));const ref=stableId("work","test",root),work=workAt(root,[document(ref,"one.md","content")]);const first=new WritingStore(work);try{await first.index("rebuild");}finally{first.close();}const dir=join(root,".writing-index",work.workRef.replace(":","-")),lock=join(dir,"write.lock");await writeFile(lock,JSON.stringify({pid:2147483647,token:"stale-test-owner"}));const second=new WritingStore(work);try{expect((await second.index("incremental")).freshness).toBe("fresh");}finally{second.close();}expect(await readdir(dir)).not.toContain("write.lock");await rm(root,{recursive:true,force:true});});

  test("records bracket references that cannot resolve to a known entity",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-unresolved-"));const ref=stableId("work","test",root);const work=workAt(root,[document(ref,"notes.md","调查目标是 [[未知人物]]。")]);const store=new WritingStore(work);try{await store.index("rebuild");}finally{store.close();}const db=new DatabaseSync(indexPath(work),{readOnly:true});try{expect(db.prepare("SELECT text,reason,revision FROM unresolved_mentions").all()).toEqual([{text:"未知人物",reason:"NO_MATCHING_ENTITY",revision:1}]);}finally{db.close();await rm(root,{recursive:true,force:true});}});

  test("creates evidence-backed native nodes and deterministic graph edges",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-graph-"));const ref=stableId("work","test",root);const make=(relativePath:string,title:string,kind:SourceDocument["kind"],content:string,chapterNumber?:number):SourceDocument=>({documentRef:stableId("doc",ref,relativePath),relativePath,absolutePath:relativePath,title,kind,content,chapterNumber,sourceMtimeMs:1,sourceSize:content.length});const work=workAt(root,[make("characters.md","林秋","character","# 林秋\n调查员。"),make("location.md","地点：北塔","document","# 地点：北塔\n旧塔。"),make("one.md","第一章","chapter","# 第一章\n林秋抵达 [[北塔]]。",1),make("two.md","第二章","chapter","# 第二章\n继续调查。",2),make("outline.md","主线大纲","outline","# 主线大纲\n调查失火。"),make("hooks.md","月纹徽章","foreshadow","# 月纹徽章\n尚未回收。")]);const store=new WritingStore(work);try{await store.index("rebuild");}finally{store.close();}const db=new DatabaseSync(indexPath(work),{readOnly:true});try{const kinds=(db.prepare("SELECT kind,COUNT(*) count FROM entities GROUP BY kind").all() as Array<{kind:string;count:number}>).map(row=>row.kind);expect(kinds).toEqual(expect.arrayContaining(["Chapter","Character","Foreshadow","Location","OutlineNode"]));const edgeKinds=(db.prepare("SELECT DISTINCT kind FROM edges").all() as Array<{kind:string}>).map(row=>row.kind);expect(edgeKinds).toEqual(expect.arrayContaining(["contains","appears_in","mentions","precedes"]));expect(db.prepare("SELECT COUNT(*) count FROM unresolved_mentions").get()).toEqual({count:0});const evidence=db.prepare("SELECT content_hash,properties_json,revision FROM edges WHERE kind='precedes'").get() as {content_hash:string;properties_json:string;revision:number};expect(evidence.content_hash).toMatch(/^[a-f0-9]{64}$/);expect(JSON.parse(evidence.properties_json)).toEqual({order:1});expect(evidence.revision).toBe(1);}finally{db.close();await rm(root,{recursive:true,force:true});}});

  test("fully rebuilds equivalent derived state after the index is deleted",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-recreate-"));const ref=stableId("work","test",root);const work=workAt(root,[document(ref,"chapter.md","# 第一章\n铜钥匙打开北塔。")]);const first=new WritingStore(work);let originalRefs:string[];try{await first.index("rebuild");const result=await first.explore("search","铜钥匙");originalRefs=result.results.map(item=>item.ref);}finally{first.close();}await rm(join(root,".writing-index"),{recursive:true,force:true});const second=new WritingStore(work);try{const rebuilt=await second.index("rebuild");expect(rebuilt.stats.documents).toBe(1);expect((await second.explore("search","铜钥匙")).results.map(item=>item.ref)).toEqual(originalRefs!);}finally{second.close();await rm(root,{recursive:true,force:true});}});

  test("records schema v3 work, semantic snapshot, temporal and revision evidence",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-v3-"));const ref=stableId("work","test",root);const chapter:SourceDocument={...document(ref,"one.md","# 第一章\n证据。"),title:"第一章",kind:"chapter",chapterNumber:1};const work=workAt(root,[chapter]);const store=new WritingStore(work);try{await store.index("rebuild");}finally{store.close();}const db=new DatabaseSync(indexPath(work),{readOnly:true});try{expect(db.prepare("SELECT schema_version,current_revision FROM works").get()).toEqual({schema_version:3,current_revision:1});const revision=db.prepare("SELECT source_snapshot_hash,status,software_version FROM index_revisions").get() as {source_snapshot_hash:string;status:string;software_version:string};expect(revision.source_snapshot_hash).toMatch(/^[a-f0-9]{64}$/);expect(revision.status).toBe("valid");expect(revision.software_version).toBe("0.1.0");const stored=db.prepare("SELECT source_ordinal,source_start_line,content_hash,semantic_hash FROM documents").get() as {source_ordinal:number;source_start_line:number;content_hash:string;semantic_hash:string};expect(stored).toMatchObject({source_ordinal:0,source_start_line:1});expect(stored.content_hash).toMatch(/^[a-f0-9]{64}$/);expect(stored.semantic_hash).toMatch(/^[a-f0-9]{64}$/);expect(stored.semantic_hash).not.toBe(stored.content_hash);const entity=db.prepare("SELECT content_hash,valid_from_chapter,valid_to_chapter,properties_json,revision FROM entities WHERE kind='Chapter'").get() as {content_hash:string;valid_from_chapter:string;valid_to_chapter:string;properties_json:string;revision:number};expect(entity.content_hash).toMatch(/^[a-f0-9]{64}$/);expect(entity.valid_from_chapter).toBe(entity.valid_to_chapter);expect(JSON.parse(entity.properties_json)).toEqual({documentKind:"chapter"});expect(entity.revision).toBe(1);}finally{db.close();await rm(root,{recursive:true,force:true});}});
  test("incremental indexing preserves derived rows outside the affected scope",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-scope-"));const ref=stableId("work","test",root);const make=(path:string,content:string,kind:SourceDocument["kind"]="document"):SourceDocument=>({...document(ref,path,content,path==="character.md"?1:path==="chapter.md"?2:3),kind,title:path});const original=workAt(root,[make("character.md","# Alice","character"),make("chapter.md","# Opening\nAlice entered.","chapter"),make("notes.md","initial notes")]);const first=new WritingStore(original);try{await first.index("rebuild");}finally{first.close();}const changed=workAt(root,[make("character.md","# Alice","character"),make("chapter.md","# Opening\nAlice entered.","chapter"),make("notes.md","updated notes")]);const second=new WritingStore(changed);try{const result=await second.index("incremental");expect(result.revision).toBe(2);}finally{second.close();}const db=new DatabaseSync(indexPath(changed),{readOnly:true});try{const row=db.prepare("SELECT m.revision FROM mentions m JOIN spans s ON s.span_ref=m.span_ref JOIN documents d ON d.document_ref=s.document_ref WHERE d.relative_path='chapter.md' AND m.source_kind='deterministic'").get();expect(row).toEqual({revision:1});}finally{db.close();await rm(root,{recursive:true,force:true});}});

  test("entity changes refresh references in otherwise unchanged documents",async()=>{const root=await mkdtemp(join(tmpdir(),"writing-mcp-entity-scope-"));const ref=stableId("work","test",root);const make=(path:string,content:string,kind:SourceDocument["kind"]="document"):SourceDocument=>({...document(ref,path,content,path==="character.md"?1:2),kind,title:path});const unresolved=workAt(root,[make("character.md","# Characters","character"),make("chapter.md","# Opening\n[[Bob]] arrived.","chapter")]);const first=new WritingStore(unresolved);try{await first.index("rebuild");}finally{first.close();}const resolved=workAt(root,[make("character.md","# Bob","character"),make("chapter.md","# Opening\n[[Bob]] arrived.","chapter")]);const second=new WritingStore(resolved);try{await second.index("incremental");}finally{second.close();}const db=new DatabaseSync(indexPath(resolved),{readOnly:true});try{expect(db.prepare("SELECT COUNT(*) count FROM unresolved_mentions").get()).toEqual({count:0});expect(db.prepare("SELECT COUNT(*) count FROM edges WHERE kind='mentions'").get()).toEqual({count:1});expect(db.prepare("SELECT revision FROM mentions WHERE source_kind='native'").get()).toEqual({revision:2});}finally{db.close();await rm(root,{recursive:true,force:true});}});
});
