import { readFile, readdir, stat } from "node:fs/promises";
import { basename, join, relative } from "node:path";
import { assertWithin, safeRealpath, stableId, type DocumentKind, type ParsedWork, type SourceDocument, type WorkAdapter, type WorkCandidate } from "@writing-mcp/core";

async function exists(path:string){try{await stat(path);return true;}catch{return false;}}
async function markdownFiles(dir:string,root?:string,visited=new Set<string>()):Promise<string[]>{if(!await exists(dir))return[];const real=await safeRealpath(dir),safeRoot=root??real;assertWithin(safeRoot,real);if(visited.has(real))return[];visited.add(real);const out:string[]=[];for(const e of await readdir(real,{withFileTypes:true})){const p=await safeRealpath(join(real,e.name));assertWithin(safeRoot,p);if(e.isDirectory())out.push(...await markdownFiles(p,safeRoot,visited));else if(/\.md$/i.test(e.name))out.push(p);}return out.sort();}
const chapterNumber=(name:string)=>Number(name.match(/(\d+)/)?.[1])||undefined;

export class InkosAdapter implements WorkAdapter {
  readonly kind="inkos" as const;
  async discover(sourcePath:string):Promise<WorkCandidate[]>{try{const real=await safeRealpath(sourcePath);let projectRoot=real;if(basename(real).toLowerCase()==="inkos.json")projectRoot=join(real,"..");if(!await exists(join(projectRoot,"inkos.json")))return[];const books=join(projectRoot,"books");if(!await exists(books))return[];const candidates:WorkCandidate[]=[];for(const id of await readdir(books)){const root=join(books,id),config=join(root,"book.json");if(!await exists(config))continue;let title=id;try{title=JSON.parse(await readFile(config,"utf8")).title??id;}catch{}candidates.push({workRef:stableId("work","inkos",projectRoot,id),title,rootPath:root,adapter:this.kind,capabilities:["chapters","characters","outline","state","foreshadow"]});}return candidates;}catch{return[];}}
  async load(candidate:WorkCandidate):Promise<ParsedWork>{const paths:Array<{path:string;kind:DocumentKind}>=[];const root=candidate.rootPath;for(const [rel,kind] of [["story/outline/story_frame.md","outline"],["story/story_bible.md","outline"],["story/outline/volume_map.md","outline"],["story/volume_outline.md","outline"],["story/current_state.md","state"],["story/pending_hooks.md","foreshadow"],["story/book_rules.md","document"]] as const){const p=join(root,rel);if(await exists(p))paths.push({path:p,kind});}
    for(const p of await markdownFiles(join(root,"story","roles")))paths.push({path:p,kind:"character"});if(!paths.some(p=>p.kind==="character")){const legacy=join(root,"story","character_matrix.md");if(await exists(legacy))paths.push({path:legacy,kind:"character"});}for(const p of await markdownFiles(join(root,"chapters")))paths.push({path:p,kind:"chapter"});
    const realRoot=await safeRealpath(root);const documents:SourceDocument[]=[];for(const entry of paths){const real=await safeRealpath(entry.path);assertWithin(realRoot,real);const content=await readFile(real,"utf8"),info=await stat(real),rel=relative(realRoot,real).replaceAll("\\","/");const title=content.match(/^#\s+(.+)$/m)?.[1]?.trim()??basename(real,".md");documents.push({documentRef:stableId("doc",candidate.workRef,rel),relativePath:rel,absolutePath:real,title,kind:entry.kind,content,chapterNumber:entry.kind==="chapter"?chapterNumber(basename(real)):undefined,sourceMtimeMs:info.mtimeMs,sourceSize:info.size});}return{...candidate,documents};}
}
