import { execFileSync } from "node:child_process";
import { rename, writeFile } from "node:fs/promises";
import { isAbsolute, relative, resolve } from "node:path";
import { measureGoldEvidence, goldSnapshot } from "./gold-measurement.mjs";
const gitState = () => ({ head: execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim(), dirty: execFileSync("git", ["status", "--porcelain"], { encoding: "utf8" }) });
const explicitTarget = process.env.WRITING_MCP_GOLD_BASELINE_PATH ? resolve(process.env.WRITING_MCP_GOLD_BASELINE_PATH) : undefined;
const repositoryRoot = resolve(execFileSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" }).trim());
const targetRelative = explicitTarget ? relative(repositoryRoot, explicitTarget) : "";
const externalControlledTarget = explicitTarget !== undefined && (targetRelative.startsWith("..") || isAbsolute(targetRelative));
const before = gitState();
if (before.dirty && !externalControlledTarget) throw new Error("gold:update requires a clean HEAD; commit or stash changes before measuring");
const measurement = await measureGoldEvidence(process.env.WRITING_MCP_PRIVATE_ACCEPTANCE);
if (measurement.verdict !== "PASS") throw new Error("Candidate gold gates failed; baseline was not updated");
const after = gitState();
if (after.head !== before.head || after.dirty !== before.dirty) throw new Error("gold:update refused because HEAD or worktree changed during measurement");
const target = explicitTarget ?? new URL("../reports/gold-evidence-baseline.json", import.meta.url);
const temporary = typeof target === "string" ? `${target}.${process.pid}.tmp` : new URL(`../reports/.gold-evidence-${process.pid}.tmp`, import.meta.url);
const gitCommit = before.head;
await writeFile(temporary, JSON.stringify(goldSnapshot(measurement, gitCommit), null, 2) + "\n", "utf8");
await rename(temporary, target);
console.error(`[gold:update] wrote ${typeof target === "string" ? target : target.pathname} for ${gitCommit}`);
